import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";

const saiyanSans = localFont({
  src: "./fonts/Saiyan-Sans.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${saiyanSans.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
